
import { test, expect } from '@playwright/test';

test.describe('Job Creation', () => {
  test.beforeEach(async ({ page }) => {
    // Mock the API key in local storage to ensure the form is enabled.
    await page.addInitScript(() => {
      window.localStorage.setItem('jules-api-key', '"test-api-key"');
    });
    // Mock the new job in local storage to simulate a successful API call.
    await page.addInitScript(() => {
      const mockJobs = [
        {
          id: 'session-123',
          name: 'Test Job from E2E Test',
          prompt: 'This is a test prompt from an E2E test.',
          sessionIds: ['session-123'],
          createdAt: new Date().toISOString(),
        },
      ];
      window.localStorage.setItem('jules-jobs', JSON.stringify(mockJobs));
    });
  });

  test('should allow a user to create a new job and see it in the list', async ({
    page,
  }) => {
    // Navigate to the home page.
    await page.goto('/');

    // Fill in the text area with a new prompt.
    const promptText = 'This is a test prompt from an E2E test.';
    await page.getByPlaceholder('Enter one or more prompts...').fill(promptText);

    // Click the "Create Jobs" button.
    await page.getByRole('button', { name: 'Create Jobs' }).click();

    // Expect to see a toast notification for successful job creation.
    await expect(page.getByText('Jobs Created')).toBeVisible();

    // The job list should now contain the newly created job.
    // We will look for the job by its name, which is generated by the AI flow.
    // Since we are mocking the API call, we will look for the mock job name.
    await expect(page.getByText('Test Job from E2E Test')).toBeVisible();
  });
});
