// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               v5.29.3
// source: google/protobuf/go_features.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "pb";

export interface GoFeatures {
  /** Whether or not to generate the deprecated UnmarshalJSON method for enums. */
  legacyUnmarshalJsonEnum?:
    | boolean
    | undefined;
  /** One of OPEN, HYBRID or OPAQUE. */
  apiLevel?: GoFeatures_APILevel | undefined;
}

export enum GoFeatures_APILevel {
  /**
   * API_LEVEL_UNSPECIFIED - API_LEVEL_UNSPECIFIED results in selecting the OPEN API,
   * but needs to be a separate value to distinguish between
   * an explicitly set api level or a missing api level.
   */
  API_LEVEL_UNSPECIFIED = 0,
  API_OPEN = 1,
  API_HYBRID = 2,
  API_OPAQUE = 3,
  UNRECOGNIZED = -1,
}

export function goFeatures_APILevelFromJSON(object: any): GoFeatures_APILevel {
  switch (object) {
    case 0:
    case "API_LEVEL_UNSPECIFIED":
      return GoFeatures_APILevel.API_LEVEL_UNSPECIFIED;
    case 1:
    case "API_OPEN":
      return GoFeatures_APILevel.API_OPEN;
    case 2:
    case "API_HYBRID":
      return GoFeatures_APILevel.API_HYBRID;
    case 3:
    case "API_OPAQUE":
      return GoFeatures_APILevel.API_OPAQUE;
    case -1:
    case "UNRECOGNIZED":
    default:
      return GoFeatures_APILevel.UNRECOGNIZED;
  }
}

export function goFeatures_APILevelToJSON(object: GoFeatures_APILevel): string {
  switch (object) {
    case GoFeatures_APILevel.API_LEVEL_UNSPECIFIED:
      return "API_LEVEL_UNSPECIFIED";
    case GoFeatures_APILevel.API_OPEN:
      return "API_OPEN";
    case GoFeatures_APILevel.API_HYBRID:
      return "API_HYBRID";
    case GoFeatures_APILevel.API_OPAQUE:
      return "API_OPAQUE";
    case GoFeatures_APILevel.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

function createBaseGoFeatures(): GoFeatures {
  return { legacyUnmarshalJsonEnum: false, apiLevel: 0 };
}

export const GoFeatures: MessageFns<GoFeatures> = {
  encode(message: GoFeatures, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.legacyUnmarshalJsonEnum !== undefined && message.legacyUnmarshalJsonEnum !== false) {
      writer.uint32(8).bool(message.legacyUnmarshalJsonEnum);
    }
    if (message.apiLevel !== undefined && message.apiLevel !== 0) {
      writer.uint32(16).int32(message.apiLevel);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GoFeatures {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGoFeatures();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.legacyUnmarshalJsonEnum = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.apiLevel = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GoFeatures {
    return {
      legacyUnmarshalJsonEnum: isSet(object.legacyUnmarshalJsonEnum)
        ? globalThis.Boolean(object.legacyUnmarshalJsonEnum)
        : isSet(object.legacy_unmarshal_json_enum)
        ? globalThis.Boolean(object.legacy_unmarshal_json_enum)
        : false,
      apiLevel: isSet(object.apiLevel)
        ? goFeatures_APILevelFromJSON(object.apiLevel)
        : isSet(object.api_level)
        ? goFeatures_APILevelFromJSON(object.api_level)
        : 0,
    };
  },

  toJSON(message: GoFeatures): unknown {
    const obj: any = {};
    if (message.legacyUnmarshalJsonEnum !== undefined && message.legacyUnmarshalJsonEnum !== false) {
      obj.legacyUnmarshalJsonEnum = message.legacyUnmarshalJsonEnum;
    }
    if (message.apiLevel !== undefined && message.apiLevel !== 0) {
      obj.apiLevel = goFeatures_APILevelToJSON(message.apiLevel);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GoFeatures>, I>>(base?: I): GoFeatures {
    return GoFeatures.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GoFeatures>, I>>(object: I): GoFeatures {
    const message = createBaseGoFeatures();
    message.legacyUnmarshalJsonEnum = object.legacyUnmarshalJsonEnum ?? false;
    message.apiLevel = object.apiLevel ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
